### ISSUE TITLE
subaru USING.txt 

### ISSUE THREAD

**Issue by fenugrec** [fenugrec/npkern#12]
@rimwall

- examples use `flblock` wrong. It's tricky to use; the .bin file must be from the desired block (and not the complete ROM). Better just explain how to use `flrom` which covers >99% of use cases.
- should mention usage `dm testdump.bin 0 0`  : with the last arg=0, it will automatically dump the correct size, if `setdev` was done
- (minor) , `the kernel ID number will be reported` should be `the kernel build ID `
-

**Comment by rimwall** [comment]
> the .bin file must be from the desired block (and not the complete ROM)

I don't think so. This is what the mini-help from nisprog says:

```
	{ "flblock", "flblock <romfile> <blockno> [Y]", "Reflash a single block from <romfile>. "
							"If 'Y' is absent, this runs in \"practice\" mode (without modifying flash ROM).\n"
							"ex.: \"flblock wholerom.bin 15 Y\"\n",
			cmd_flblock, 0, NULL},
```
...and every time I've used flblock (successfully), I have used a .bin file that is 1MB in size.

Anyway, I agree with only mentioning flrom, so I will update accordingly. I have fixed the other two items as well. Updated file is in a ssmk_test branch.

**Comment by fenugrec** [comment]
> I don't think so.

Heh you're absolutely right. I was confusing the old test commands that I used before adding flblock, and those did need a trimmed .bin file. 


> Anyway, I agree with only mentioning flrom, so I will update accordingly.

Excellent, thanks. Will review and merge.

**Comment by rimwall** [comment]
This is done and ready for merge. I have recreated my repo as a fresh fork, and this change is done in branch 'ssmk_test'

**Comment by fenugrec** [comment]
Merged in 7fa074. thanks !
