### ISSUE TITLE
support request: GCC cross compiler

### ISSUE THREAD

**Issue by ConnorRigby** [fenugrec/npkern#14]
Thanks so much for this project! i'm in the process of implementing a CAN command handler using ISO TP and UDS, i've almost finished the implementation  and have tested on Linux. My issue now is i'm having a hard time finding a good GCC cross compiler, i see that GCC has support for sh processors, but i haven't been able to find one that compiles code correctly. Any help here would be great.

What i've tried so far was downloading GCC and Binutils, I've compiled them with something that looks like

```bash
export TARGET=sh4-elf
export PREFIX=$PWD/cross

#binutils
git clone git://sourceware.org/git/binutils-gdb.git binutils
mkdir binutils/build
cd binutils/build
../configure --target=$TARGET --prefix="$PREFIX" --with-sysroot --disable-nls --disable-werror
make
make install
cd ..

git clone git://gcc.gnu.org/git/gcc.git
mkdir gcc/build
cd gcc/build
../configure --target=$TARGET --prefix="$PREFIX" --disable-nls --enable-languages=c --without-headers
make all-gcc
make all-target-libgcc
make install-gcc
make install-target-libgcc
```

this leaves me with what *looks* like a valid cross compiler in $PREFIX, however when i try to compile npkern (without my changes by the way), i get a `unknown machine -m2`. The GCC docs say that it should support SH2, however i can't quite figure out how to enable it.. Any ideas would be helpful

**Comment by fenugrec** [comment]
producing a good cross-compiler is a bit of a nightmare. Look at your distro's packages ? Sometimes dreamcast enthusiasts package a baremetal sh compiler.
I'm on Arch, I'm using this https://aur.archlinux.org/packages/sh-elf-gcc  ( + corresponding  binutils + newlib).

I've also used https://crosstool-ng.github.io/ in the past; it has a sample config `sh-unknown-elf` that should work. I remember working on endianness and multillib issues with the dev a while ago.

**Comment by ConnorRigby** [comment]
Thanks, i didn't realize crosstool has a sh config, maybe i'll try that next.
I use arch, but that package didn't build for me, maybe i'll try again. I *think* i've got the correct configuration for GCC, it finally got the correct machine+arch, but failed when including string.h, presumably because i skipped building a libc or something.

**Comment by ConnorRigby** [comment]
My issue with the AUR package was that the mirror for ISL was down. Waiting for a build right now, but i think this should work. Will report back

**Comment by ConnorRigby** [comment]
Welp, it took a few tries - but i was able to get crosstool to build me a toolchain. I will Try to make some time to create documentation for this. In the meantime, if someone finds this in the future, the gist of what i did was
1) install crosstool.ng
2) change to big endian

This allowed me to compile npkern, and loading it into ghidra *looks* like it should work, but i haven't actually tested it yet
