### ISSUE TITLE
Compiling 7051 kernel

### ISSUE THREAD

**Issue by rimwall** [fenugrec/npkern#8]
Hi, I've have bypassed this issue now by not compiling the 7051 kernel, but I thought I should raise it just in case it causes bigger problems somewhere. I couldn't get it to compile. I'm very new to Cmake, so I could be something I'm doing. Cmake output below...

C:\NisProg\Editing\NPK_Master>cmake -G "MinGW Makefiles" -S c:\nisprog\editing\npk_master -B c:\nisprog\editing\npk_master\bin -DCMAKE_TOOLCHAIN_FILE=/nisprog/editing/npk_master/cmake/toolchain-sh.cmake
Using install prefix : C:/NisProg/Editing/NPK_Master/bin
-- The C compiler identification is GNU 4.7.0
-- The ASM compiler identification is GNU
-- Found assembler: /Program Files (x86)/KPIT/GNUSHv13.01-ELF/sh-elf/bin/sh-elf-gcc.exe
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Progra~2/KPIT/GNUSHv13.01-ELF/sh-elf/bin/sh-elf-gcc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- SH7051
-- SH7055_35
-- SH7055_18
-- SH7058
-- Configuring done
-- Generating done
-- Build files have been written to: C:/NisProg/Editing/NPK_Master/bin

C:\NisProg\Editing\NPK_Master>cmake --build c:\nisprog\editing\npk_master\bin\
[  0%] Built target version_h
Scanning dependencies of target npk_SH7051
[  3%] Building C object CMakeFiles/npk_SH7051.dir/cmd_parser.c.obj
[  6%] Building C object CMakeFiles/npk_SH7051.dir/eep_funcs.c.obj
[  9%] Building C object CMakeFiles/npk_SH7051.dir/main.c.obj
C:\NisProg\Editing\NPK_Master\main.c:72:6: warning: return type of 'main' is not 'int' [-Wmain]
[ 12%] Building C object CMakeFiles/npk_SH7051.dir/crc.c.obj
[ 15%] Building ASM object CMakeFiles/npk_SH7051.dir/start_705x.s.obj
[ 18%] Building C object CMakeFiles/npk_SH7051.dir/platf_7050.c.obj
[ 21%] Building C object CMakeFiles/npk_SH7051.dir/pl_flash_7051.c.obj
[ 25%] Linking C executable npk_SH7051
c:/progra2/kpit/gnushv13.01-elf/sh-elf/bin/../lib/gcc/sh-elf/4.7-GNUSH_v13.01/../../../../sh-elf/bin/ld.exe: npk_SH7051 section '.bss' will not fit in region 'RJFIX'
c:/progra2/kpit/gnushv13.01-elf/sh-elf/bin/../lib/gcc/sh-elf/4.7-GNUSH_v13.01/../../../../sh-elf/bin/ld.exe: region 'RJFIX' overflowed by 4 bytes
collect2.exe: error: ld returned 1 exit status
CMakeFiles\npk_SH7051.dir\build.make:190: recipe for target 'npk_SH7051' failed
mingw32-make.exe[2]: *** [npk_SH7051] Error 1
CMakeFiles\Makefile2:114: recipe for target 'CMakeFiles/npk_SH7051.dir/all' failed
mingw32-make.exe[1]: *** [CMakeFiles/npk_SH7051.dir/all] Error 2
Makefile:89: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2

**Comment by fenugrec** [comment]
Unfortunately that version of gcc from KPIT is very old. Current versions seem to do a better job of compiling / optimizing for size, but I hadn't noticed the 7051 kernel was so close to the limit.

**Comment by rimwall** [comment]
Yep, fixed. Thanks.
